namespace BinaryOmen.Vrika.Wpf
{
    /// <summary>
    /// List of available icons for use with <see cref="Icon"/>.
    /// </summary>
    /// <remarks>
    /// All icons sourced from Material Design Icons Font - <see cref="https://wpficons.com/"/> - in accordance of 
    /// <see cref="https://github.com/Templarian/wpf/blob/master/license.txt"/>.
    /// </remarks>
    public enum IconType
    {
        AutoGeneratedDoNotAmend
    }
}